### ISSUE TITLE
model link dead

### ISSUE THREAD

**Issue by germal** [raskolnikov-reborn/CarND-P13-System-Integration#6]
Hi !

The model link is dead , could you please re-upload the model ?
Thanks a lot
Germal

**Comment by raskolnikov-reborn** [comment]
Sorry, I ran out of google drive space and got rid of a bunch of models , databases etc from my google drive. I don't have the model anymore. You can reach out to marc.puig@gmail.com who was the person who wrote the training code and see if he can send it to you directly, or Upload somewhere and create a link, and create a merge request so I can update it as well.
